### Overview
In this project, I am analyzing a comprehensive Netflix dataset to uncover key content trends and patterns. The end goal is to deliver actionable business insights and strategic recommendations.

This project follows a structured, multi-step workflow where each task builds upon the outputs of the previous stage:
1. **Task 1:** Prepare and organize the Netflix dataset for business analytics and reporting.
2. **Task 2:** Content Type Analysis Dashboard (Movies vs. TV Shows).
3. *(Subsequent analysis tasks)*

---


Shall We?

## Task 1 - Netflix Data Cleaning & Preparation

### Importing the dataset using python and pandas

In [1]:
#Pandas(Python Library)to load the csv
#This code was run locally and cannot run because the dataset is not in this repository.
import pandas as pd
#loading the file
df_netflix = pd.read_csv('Dataset.csv')

### Identifying and Handling Missing Values

In [2]:
#Using .info() to get a concise summary of our dataset
#i.e., row count, column count, missing values and column data types.
df_netflix.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 1.6 MB

From the output above, There are no missing values. We can view our dataset using `.head()` , `.tail()` and `sample()`

In [3]:
#Viewing the firt five rows
df_netflix.head(5)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [4]:
#Viewing the last 5 rows
df_netflix.tail(5)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [5]:
#Randomly viewing 50 rows in the dataset
df_netflix.sample(50)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
7011,s1747,TV Show,Can You Hear Me?,Not Given,Canada,11/2/2020,2020,TV-MA,2 Seasons,"International TV Shows, TV Comedies, TV Dramas"
5754,s7864,Movie,Revenge of the Green Dragons,"Andrew Lau Wai-Keung, Andrew Loo",Hong Kong,7/21/2018,2014,R,95 min,"Action & Adventure, Dramas, Independent Movies"
248,s177,Movie,The Golden Child,Michael Ritchie,United States,9/1/2021,1986,PG-13,94 min,"Action & Adventure, Comedies"
622,s455,Movie,Cheech & Chong's Still Smokin,Tommy Chong,Not Given,7/15/2021,1983,TV-MA,91 min,"Comedies, Cult Movies"
3580,s4951,Movie,John Mulaney: New in Town,Ryan Polito,United States,4/1/2018,2012,TV-MA,60 min,Stand-Up Comedy
8072,s5140,TV Show,Dhia Sofea,Not Given,Malaysia,12/1/2017,2015,TV-14,1 Season,"International TV Shows, TV Dramas"
2397,s3059,Movie,Garfield's Fun Fest,"Mark A.Z. Dippé, Eondeok Han",United States,1/1/2020,2008,TV-Y7,79 min,"Children & Family Movies, Comedies"
5249,s7201,Movie,Kill Hitler! The Luck of the Devil,Frédéric Tonolli,France,5/1/2019,2015,TV-14,53 min,"Documentaries, International Movies"
6053,s8225,Movie,The Brawler,Ken Kushner,United States,5/18/2019,2019,TV-MA,95 min,"Dramas, Independent Movies, Sports Movies"
6597,s109,TV Show,Dive Club,Not Given,Australia,9/3/2021,2021,TV-G,1 Season,"Kids' TV, TV Dramas, Teen TV Shows"
3135,s4296,Movie,F.R.E.D.I.,Sean Olson,United States,12/15/2018,2018,TV-PG,90 min,"Children & Family Movies, Sci-Fi & Fantasy"
6104,s8286,Movie,The Dukes of Hazzard: The Beginning,Robert Berlinger,United States,1/1/2020,2007,R,95 min,"Action & Adventure, Comedies"
5614,s7662,Movie,One Direction: This Is Us,Morgan Spurlock,United States,10/1/2019,2013,PG,92 min,"Documentaries, Music & Musicals"
4364,s6086,Movie,Across the Universe,Julie Taymor,United States,1/1/2019,2007,PG-13,133 min,"Dramas, Music & Musicals, Romantic Movies"
7155,s2185,TV Show,Get Even,Not Given,United Kingdom,7/31/2020,2020,TV-PG,1 Season,"British TV Shows, Crime TV Shows, Internationa..."
3432,s4735,Movie,Tamasha,Imtiaz Ali,India,8/2/2018,2015,TV-14,133 min,"Dramas, International Movies, Romantic Movies"
5689,s7755,Movie,Pope Francis: A Man of His Word,Wim Wenders,Switzerland,1/3/2019,2018,PG,96 min,"Documentaries, Faith & Spirituality, Internati..."
5190,s7129,Movie,Jewel's Catch One,C. Fitz,United States,5/1/2018,2016,TV-MA,84 min,"Documentaries, LGBTQ Movies"
565,s410,Movie,Chhota Bheem & Krishna: Pataliputra- City of t...,Rajiv Chilaka,India,7/22/2021,2010,TV-Y7,66 min,Children & Family Movies
2711,s3575,Movie,Simon Amstell: Set Free,Julia Knowles,United Kingdom,8/20/2019,2019,TV-MA,52 min,Stand-Up Comedy
818,s717,Movie,FTA,Francine Parker,United States,6/15/2021,1972,TV-MA,104 min,Documentaries
4635,s6420,Movie,Cardboard Gangsters,Mark O'Connor,Ireland,9/15/2018,2016,TV-MA,92 min,"Dramas, International Movies"
640,s7763,TV Show,Power Rangers Dino Super Charge,Not Given,Pakistan,10/15/2016,2016,TV-Y7,1 Season,Kids' TV
8392,s6458,TV Show,Chef & My Fridge,Not Given,South Korea,8/4/2017,2017,TV-PG,2 Seasons,"International TV Shows, Korean TV Shows, Reali..."
5782,s7897,TV Show,Royal Pains,Jay Chandrasekhar,United States,5/18/2017,2016,TV-PG,8 Seasons,"TV Comedies, TV Dramas"
7620,s3657,TV Show,Rookie Historian Goo Hae-Ryung,Not Given,South Korea,7/18/2019,2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman..."
8279,s5806,TV Show,The Fierce Wife,Not Given,Taiwan,9/1/2016,2010,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8401,s6499,TV Show,Click for Murder,Not Given,United Kingdom,9/17/2017,2017,TV-14,1 Season,"British TV Shows, Crime TV Shows, Docuseries"
4279,s5993,Movie,16 Blocks,Richard Donner,United States,11/1/2019,2006,PG-13,102 min,Action & Adventure
1753,s2092,Movie,The Bridge Curse,Lester Hsi,Taiwan,8/27/2020,2020,TV-MA,88 min,"Horror Movies, International Movies, Thrillers"
5539,s7564,Movie,National Parks Adventure,Greg MacGillivray,United States,2/1/2018,2016,TV-G,42 min,Documentaries
1130,s1156,Movie,Marked,Nadine Ibrahim,Nigeria,3/28/2021,2021,TV-PG,21 min,"Documentaries, International Movies"
324,s231,Movie,The River Runner,Rush Sturges,Not Given,8/25/2021,2021,TV-MA,86 min,"Documentaries, Sports Movies"
3158,s4334,Movie,Blind Detective,Johnnie To,Hong Kong,12/1/2018,2013,TV-MA,130 min,"Action & Adventure, Comedies, International Mo..."
6947,s1549,TV Show,The Challenge,Not Given,United States,12/15/2020,2006,TV-14,2 Seasons,Reality TV
4001,s5583,Movie,Amy Schumer: The Leather Special,Amy Schumer,United States,3/7/2017,2017,TV-MA,57 min,Stand-Up Comedy
3730,s5177,Movie,Mea Culpa,"Raúl Campos, Jan Suter",Mexico,11/10/2017,2017,TV-MA,54 min,Stand-Up Comedy
2365,s3000,TV Show,The Ghost Bride,Quek Shio-chuan,Taiwan,1/23/2020,2020,TV-14,1 Season,"International TV Shows, TV Dramas, TV Mysteries"
6777,s921,TV Show,Selena: The Series,Not Given,Mexico,5/4/2021,2020,TV-PG,2 Seasons,TV Dramas
6247,s8456,Movie,The Pirate Fairy,Peggy Holmes,United States,6/15/2014,2014,G,78 min,Children & Family Movies
3157,s4333,Movie,Battle,Katarina Launing,Norway,12/1/2018,2018,TV-MA,98 min,"Dramas, International Movies, Romantic Movies"
5779,s7892,Movie,Room on the Broom,"Max Lang, Jani Lachauer",United Kingdom,7/1/2019,2012,TV-Y7,26 min,"Children & Family Movies, Independent Movies"
7805,s4179,TV Show,Marvel's The Punisher,Not Given,United States,1/18/2019,2019,TV-MA,2 Seasons,"Crime TV Shows, TV Action & Adventure, TV Thri..."
5597,s7643,Movie,Officer Downe,Shawn Crahan,United States,3/30/2017,2016,R,91 min,Action & Adventure
5516,s7536,Movie,My Entire High School Sinking Into the Sea,Dash Shaw,United States,1/23/2018,2016,PG-13,77 min,"Comedies, Independent Movies"
2648,s3478,TV Show,Gotham,Danny Cannon,United States,9/30/2019,2019,TV-MA,5 Seasons,"Crime TV Shows, TV Action & Adventure, TV Dramas"
4508,s6249,Movie,Basic Instinct,Paul Verhoeven,United States,10/1/2020,1992,R,128 min,"Classic Movies, Thrillers"
973,s943,Movie,Mystic River,Clint Eastwood,United States,5/1/2021,2003,R,138 min,"Dramas, Thrillers"
4917,s6784,Movie,Forbidden Games: The Justin Fashanu Story,"Jon Carey, Adam Darke",United Kingdom,12/1/2017,2017,TV-14,81 min,"Documentaries, International Movies, LGBTQ Movies"
5411,s7410,TV Show,Mars,Everardo Gout,United States,11/1/2019,2018,TV-PG,2 Seasons,"Docuseries, Science & Nature TV, TV Dramas"

In as much as the output in `.info()` read no missing values, after viewing our dataset, we can see in the director and country coulmns, there are some rows that read 'Not Given'. 'Not Given' is just a placeholder for NaN(None) hence pandas doesn't view it as a missng value. We can change it to NaN using the python library **Numpy**.

In [6]:
import numpy as np
# Replacing 'Not Given' placeholders with NaN
df_netflix.replace('Not Given', np.nan, inplace=True)

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,NaN,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,NaN,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,NaN,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,NaN,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,NaN,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [7]:
df_netflix.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      6202 non-null   str
 4   country       8503 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 1.5 MB

'Not Given' has been handled. From the output above, only a few titles don't have a named director but almost 30% don't have a named country.

### Removing duplicate records and formatting inconsistencies

In [8]:
#Checking if there a duplicate rows
df_netflix.duplicated().any()

np.False_

In [9]:
#Checking if there are duplicated show IDs
df_netflix.duplicated(subset=['show_id']).any()

np.False_

There are no duplicate rows or duplicated show_id's. Yahoo!

When `.info()` was first run, `string` was the datatype across all columns but one i.e., year. The string data type isn't exactly ideal when it comes to data analysis therefore we will format these inconsistencies for an easy analysis flow.

**LISTING INCONSISTENSIES**
1. **Incorrect datetime format** -
`date_added` column is currently a string data type, This hinders time-series analysis, filtering by month/year or sorting chronoliogically with strings.
2.  **Categorical columns as Strings** -
Columns like `type` and `rating` hold categorical data therefore converting them to `category` type is more memory-efficient and speeds up operations.

3. **Mixed String Columns** - Since the `duration` column contains both numeric lengths for movies (e.g., "90 min") and season counts for TV shows (e.g., "1 Season"), we can split this column into two new columns:
   * `duration_value`: A numeric column (integer) holding the count.
   * `duration_unit`: A categorical column containing the unit ('min' or 'Season').

In [10]:
# Converting date_added column to datetime format
df_netflix['date_added'] = pd.to_datetime(df_netflix['date_added'])

#Coverting 'type' and 'rating' to categorical data types and saving the changes back to df_netflix
df_netflix = df_netflix.astype({'type': 'category','rating': 'category'})

In [11]:
# Splitting 'duration' into value and unit
split_duration = df_netflix['duration'].str.split(' ', expand=True)

#Assigning new columns and cleaning up
df_netflix['duration_value'] = pd.to_numeric(split_duration[0], errors='coerce')
df_netflix['duration_unit'] = split_duration[1].str.replace('Seasons', 'Season').astype('category')

# Displaying the updated columns alongside the original columns
display(df_netflix[['title', 'type', 'duration', 'duration_value', 'duration_unit']].head(10))

,title,type,duration,duration_value,duration_unit
0,Dick Johnson Is Dead,Movie,90 min,90,min
1,Ganglands,TV Show,1 Season,1,Season
2,Midnight Mass,TV Show,1 Season,1,Season
3,Confessions of an Invisible Girl,Movie,91 min,91,min
4,Sankofa,Movie,125 min,125,min
5,The Great British Baking Show,TV Show,9 Seasons,9,Season
6,The Starling,Movie,104 min,104,min
7,Motu Patlu in the Game of Zones,Movie,87 min,87,min
8,Je Suis Karl,Movie,127 min,127,min
9,Motu Patlu in Wonderland,Movie,76 min,76,min

In [12]:
df_netflix.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8790 non-null   str
 1   type            8790 non-null   category
 2   title           8790 non-null   str
 3   director        6202 non-null   str
 4   country         8503 non-null   str
 5   date_added      8790 non-null   datetime64[us]
 6   release_year    8790 non-null   int64
 7   rating          8790 non-null   category
 8   duration        8790 non-null   str
 9   listed_in       8790 non-null   str
 10  duration_value  8790 non-null   int64
 11  duration_unit   8790 non-null   category
dtypes: category(3), datetime64[us](1), int64(2), str(6)
memory usage: 1.3 MB

### Standerdizing the Columns

Standerdizing columns like `country` , `rating`  and `type` ensures our dataset is clean, uniform and ready for data analysis.

In [13]:
#Standerdizing the three columns
for col in ['country', 'rating', 'type']:
  df_netflix[col] = df_netflix[col].astype(str).str.strip()

#Ratings in Netflix are always in uppercase
#'country' and 'type' in title is neat as they are proper nouns
  if col == 'rating':
    df_netflix[col] = df_netflix[col].str.upper()
  else:
    df_netflix[col] = df_netflix[col].str.title()

#Converting to catgeory data types
#'rating' and 'country' had gone back to object during the standerdization.
df_netflix= df_netflix.astype({'country': 'category', 'rating': 'category', 'type':'category'})

#Displaying the columns after Standerdization
display(df_netflix[['title', 'country', 'rating']].head(10))

                              title         country rating
0              Dick Johnson Is Dead   United States  PG-13
1                         Ganglands          France  TV-MA
2                     Midnight Mass   United States  TV-MA
3  Confessions of an Invisible Girl          Brazil  TV-PG
4                           Sankofa   United States  TV-MA
5     The Great British Baking Show  United Kingdom  TV-14
6                      The Starling   United States  PG-13
7   Motu Patlu in the Game of Zones           India  TV-Y7
8                      Je Suis Karl         Germany  TV-MA
9          Motu Patlu in Wonderland           India  TV-Y7

In [14]:
df_netflix.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8790 non-null   str
 1   type            8790 non-null   category
 2   title           8790 non-null   str
 3   director        6202 non-null   str
 4   country         8503 non-null   category
 5   date_added      8790 non-null   datetime64[us]
 6   release_year    8790 non-null   int64
 7   rating          8790 non-null   category
 8   duration        8790 non-null   str
 9   listed_in       8790 non-null   str
 10  duration_value  8790 non-null   int64
 11  duration_unit   8790 non-null   category
dtypes: category(4), datetime64[us](1), int64(2), str(5)
memory usage: 1.2 MB

### Exporting the cleaned datset for analysis.

In [16]:

#Saving the cleaned dataset to a new CSV file
df_netflix.to_csv("../Netflix_project/cleaned_dataset.csv", index=False)